### ISSUE TITLE
全角括弧前の制御綴

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/BXjscls#10]
https://github.com/zr-tex8r/BXjscls/blob/542f8156cf11269552cb40c986d6fa11f10953a6/bxjscls.dtx#L5850

[forum;2639#p15477](https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2639#p15477) を見ると，ここはスペースを入れたほうが安全そうです。

**Comment by zr-tex8r** [comment]
結局upTeX 1.24は闇に葬られたわけですが……。

jsclassesにも“対応する”記述がありますが、こちらに安全対策を入れる予定はあるでしょうか？

```tex
\newcommand{\labelenumii}{\inhibitglue（\theenumii）\inhibitglue}
```

こちらの方針としては「jsclassesに合わせる」ことになると思います。


---

ただ、該当の部分については、そもそも完全にマチガッテルようですね 😭 コレであるべき：

```tex
\newcommand*{\jsInJaParen}[1]{%
  \bxjs@dust\jsInhibitGlue（#1）\jsInhibitGlue\bxjs@dust}
\newcommand{\labelenumi}{\theenumi.}
\newcommand{\labelenumii}{\jsInJaParen{\theenumii}}


```

**Comment by aminophen** [comment]
> jsclassesにも“対応する”記述がありますが、こちらに安全対策を入れる予定はあるでしょうか？

ちゃんと見ていませんでした。目についたところだけ対策しました→ texjporg/jsclasses@3355f06

> ただ、該当の部分については、そもそも完全にマチガッテルようですね😭

あちゃあ。

**Comment by zr-tex8r** [comment]
v1.9hをリリースしました。
