### ISSUE TITLE
numcases環境において数式位置がおかしい

### ISSUE THREAD

**Issue by estshorter** [zr-tex8r/BXjscls#12]
casesパッケージが3.0にアップデートされて以降、numcases, subnumcases環境を使うと数式の位置が右に寄ってしまう。
casesパッケージの作者に報告すべきかとも思いましたが、jsarticleでは発生しなかったので、こちらに報告しました。

## 環境
- uplatex + dvipdfmx
- cases: 3.0, 3.1で不具合確認。それより前では起こらない。
- BXjsarticle: 2020/02/15 v1.9k BXJS document classes
- jsarticle: 2020/02/02 jsclasses (okumura, texjporg)

### texファイル
```  tex
%\documentclass[uplatex,a4paper]{jsarticle}
\documentclass[a4paper,uplatex,dvipdfmx,ja=standard]{bxjsarticle}

\usepackage{cases}
\begin{document}
\section{hoge}
fuga
\begin{numcases}{y= }
x^{10}+x^9+x^8+x^7+x^6+x^5+x^4+x^3+x^2+x+1& $0 < x < 10$  \\
0& otherwise
\end{numcases}
\end{document}
```
### コンパイル結果
[test_bxjsarticle.pdf](https://github.com/zr-tex8r/BXjscls/files/4341020/test_bxjsarticle.pdf)
[test_jsarticle.pdf](https://github.com/zr-tex8r/BXjscls/files/4341021/test_jsarticle.pdf)

**Comment by zr-tex8r** [comment]
原因がわかりました。

BXjsclsのクラスは内部でcalcパッケージを読み込んでいますが、**calcパッケージとcasesパッケージが衝突を起こしています**。つまり、calcパッケージを読み込むと、jsarticleでもarticleでも出力は異常になります。

「calcパッケージは`\settowidth`命令の内部実装を書き換えるが、現状のnumcasesの実装はこの新しい`\settowidth`の実装と互換性がない
ということなので、casesパッケージの問題であると考えられます。

**Comment by estshorter** [comment]
調査ありがとうございます。
casesパッケージの問題とのことなので、そちらの作者に問題を報告してみます。

**Comment by estshorter** [comment]
casesパッケージのv3.2で、calcパッケージとの衝突が解消されました。
参考まで。
