### ISSUE TITLE
Pandoc モードで jafont 指定するとエラーが発生してPDF生成できない

### ISSUE THREAD

**Issue by shuntaroy** [zr-tex8r/BXjscls#4]
MacTex 2017 を現時点で最新の状態 (`sudo tlmgr update --self --all`) で使っているのですが、`xelatex` エンジンで `-V classoption=jafont=ipaex` としてフォントを指定すると

```
! Too many }'s.
l.451   }
```

というエラーが出て pandoc が終了します。
`jafont` の指定を外すと正常にPDFを出力します。

pandoc のバージョンは 1.19.2.1、bxjscls のバージョンは 1.5c です。

このエラーは、

```
# test

test markdown
```

という簡単な markdown ファイルを使い、`pandoc test.md -o test.pdf --latex-engine=xelatex -V documentclass=bxjsarticle -V classoption=pandoc -V classoption=jafont=ipaex` を実行することで再現を確認しています。

また、`pandoc` の `--verbose` オプションをつけると、

```
...(略)...
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics-def/xetex.def)))))
(/usr/local/texlive/2017/texmf-dist/tex/xelatex/xunicode/xunicode.sty
*** Reloading Xunicode for encoding 'TU' ***
) (/usr/local/texlive/2017/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(/usr/local/texlive/2017/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg)))
! Too many }'s.
l.451   }
         \bxjs@next
No pages of output.
```

と出ます（抜粋）。
この出力を見る限り、xeCJK や zxjatype のほうに起因するのかもしれないので、こちらで報告するのは場違いかもしれませんが、ご報告申し上げます。

**Comment by zr-tex8r** [comment]
単純にBXjsclsのバグで、XeLaTeX上でjafontを指定した場合に必ずエラーになっていました。

修正版（v1.5d）をリリースしました。TeX Live（MacTeX）のマスタに数日中に反映されるはずです。お急ぎであれば、お手数ですが手動で最新版のインストールをお願いします。

ご報告ありがとうございました。

**Comment by shuntaroy** [comment]
当方で `jafont` の設定が動くことを確認いたしました。
ご対応ありがとうございました！
