### ISSUE TITLE
XeLaTeXでコンパイルエラー

### ISSUE THREAD

**Issue by hidaruma** [zr-tex8r/BXjscls#5]
* bxjsarticle
* OS Ubuntu
* TeXLive 2017
* XeTeX Version 3.14159265-2.6-0.99998 (TeX Live 2017)

```
\documentclass[ja=standard, xelatex]{bxjsarticle}
```

で以下のようなエラーが出ます。

```
! Too many }'s.
l.451   }
         \bxjs@next
```
bxjsja-standard.defの450行目で読み込まれるzxjafontのバージョンを[2015/05/08]にしたところ発生しなくなります。

**Comment by zr-tex8r** [comment]
#4 と同じ問題ではないでしょうか。

```latex
\documentclass[ja=standard, xelatex]{bxjsarticle}
```

この指定の場合、手元では（v1.5cでもv1.5dでも）エラーが再現しませんでした。しかし、当該のコード（451行目付近、つまりzxjafontの読込）はjafontを指定した場合にのみに実行されるものであるため、恐らく、#4 と同じく、v1.5c のバグのために `jafont` を使用したときにエラーが起こったのだと思います。

この #4 の不具合は最新版の v1.5d で既に修正されています。

**Comment by hidaruma** [comment]
放置してしまっていました。Closeします
