### ISSUE TITLE
XeLaTeXでコンパイルできない

### ISSUE THREAD

**Issue by equal-l2** [zr-tex8r/BXjscls#6]
macOS 10.12.6
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017)
bxjscls 1.5d
以上の環境で、次の書類をコンパイルするとエラーになってしまいます。
```
\documentclass[xelatex,ja=standard]{bxjsarticle}
\begin{document}
\end{document}
```
エラー：
```
! Undefined control sequence.
<argument> \cs_if_eq:p:NN

l.371 ...eq:p:NN \inhibitglue \prg_do_nothing: ) }
```

**Comment by equal-l2** [comment]
再インストールしたら直ってしまいました。
お騒がせしました。

**Comment by equal-l2** [comment]
LuaLaTeXで同様のコンパイルをすると、こちらもエラーになります。
```
! Undefined control sequence.
<recently read> \patchcmd

l.31 ...ame TU\string\textasteriskcentered\endcsname
                                                  {\char}{\ltjalchar}{}{}
```

**Comment by zr-tex8r** [comment]
申し訳ありません。これはZXjatypeパッケージの方のバグです。

把握はしているのですが、対応が遅れています。

取りあえず、GitHubに修正版（v0.6a）を上げたので、お手数ですが、こちらをご使用ください。

https://github.com/zr-tex8r/ZXjatype/releases

**Comment by equal-l2** [comment]
XeLaTeXで正常に動作することを確認しました。
ありがとうございます。

**Comment by equal-l2** [comment]
CTANの方にも反映されたようなのでクローズします。
対応ありがとうございます。
