### ISSUE TITLE
LuaLaTeXでコンパイルエラー

### ISSUE THREAD

**Issue by equal-l2** [zr-tex8r/BXjscls#7]
macOS 10.12.6
LuaTeX 1.0.4 (TeX Live 2017)
bxjscls 1.5d
zxjatype 0.6b
以上の環境で次の文書をコンパイルするとエラーになります。
```latex
\documentclass[a4paper,ja=standard,lualatex]{bxjsarticle}
\begin{document}
\end{document}
```

エラー:
```
! Undefined control sequence.
<recently read> \patchcmd

l.31 ...ame TU\string\textasteriskcentered\endcsname
                                                  {\char}{\ltjalchar}{}{}
```

**Comment by zr-tex8r** [comment]
恐らく、LuaTeX-jaの不具合だと思われます。
もしかしたら、everyhookというパッケージをインストールすれば通る（不具合回避）かもしれません。

**Comment by aminophen** [comment]
前にも似た問題があった気がしましたが，まだあったんですね。 https://ja.osdn.net/ticket/browse.php?group_id=5593&tid=37426 に書いてみました。

**Comment by equal-l2** [comment]
@zr-tex8r everyhookをインストールすると通るようになりました。ありがとうございます。
bxjsclsの不具合ではないということなので、クローズします。
