### ISSUE TITLE
XeLaTeX(・LuaLaTeX)でnomag*オプション・標準より大きなフォントサイズでunicode-mathを有効にすると数式が横長になる

### ISSUE THREAD

**Issue by tats-u** [zr-tex8r/BXjscls#8]
XeLaTeX・Lua(JIT)LaTeXで以下のTeX文書をコンパイルすると数式が横長に出力されます。

```latex
\documentclass[autodetect-engine,dvipdfmx-if-dvi,ja=standard,nomag*,14pt]{bxjsarticle}
 \usepackage{ifptex,iftex}
 \usepackage{amsmath}
 \ifptex
 \usepackage{lmodern}
 \else
 \usepackage{unicode-math}
 \fi
 \title{テスト}
 \author{テスト 太郎}
 \begin{document}
         \maketitle
         \section{オイラーの公式}
         オイラーの公式を式\ref{eq:eular}に示す。
         \begin{equation}\label{eq:eular}
                 e^{i\theta} = \cos\theta + i\sin\theta
         \end{equation}
         これに$\theta = \pi$を代入すると式\ref{eq:eular2}を得る。
         \begin{equation}\label{eq:eular2}
                 e^{-i\pi} = -1
         \end{equation}
 \end{document}
```

LuaTeX-jaの方にはすでにissueを立てています。
https://osdn.net/projects/luatex-ja/ticket/37828

**Comment by aminophen** [comment]
luatexja のチケットにコメントした時点で，私はこれは「ドキュメントに書かれている通りの仕様」だと思っていました。bxjscls-manual.pdf より：

> • nomag*:nomag と同様に、全てのページレイアウトのパラメタの値をスケールさせる。さらに、“オプ 38
ティカルサイズの調整”を実現するために、NFSS の実装コードにパッチを当てる。* この場合、mag 設定による不具合は起こらなくなるが、当然、NFSS のパッチのせいで別の不具合が起こる可能性はある。

ここにある通り，だと思います。

[TeX Wiki](https://texwiki.texjp.org/?BXjscls#we2b3036) にも

> magstyle の値をどうすればよいか迷った場合は次のように決めればよいでしょう．
> 
> - とにかく JS クラスと同じ動作にしたい場合は，既定の usemag のままにする．
> - それ以外の場合，特に「mag 機能の使用による不具合を避けたい」場合は：
>     - 本文で Computer Modern フォント（およびその派生）を用いる場合は，nomag* を指定する．
>     - そうでない場合は，nomag を指定する．

unicode-math はフォント変更を行うので，「Computer Morern フォントを用い」る場合にあたらないと考えて，nomag を使うべき状況ではないか，と思います。

なお，「LuaLaTeX でデフォルトが nomag* であることの是非」は議論に値するのかもしれません。nomag と nomag* のどちらをデフォルトにするかは，それぞれのメンテナの方が決定すればいいと思いますし，今のままでも unicode-math との併用についてドキュメントに書いてしまえば十分という考えもあり得ます。

**Comment by zr-tex8r** [comment]
まだちゃんと把握してないけど

>   「ドキュメントに書かれている通りの仕様」

「`nomag*`の想定の通り」ということかな、それとも「NFSS のパッチのせいで別の不具合が起こる」の事例ということかな？

**Comment by aminophen** [comment]
「`nomag*`の想定の通り」の方のつもりで発言しました。つまり bxjscls の `nomag*` に問題があるとまでは言えず，「マニュアルに従って使いましょう」な案件と思っていました。

**Comment by zr-tex8r** [comment]
確かに「`nomag*`の想定の通り」とはいえるのですけど、「`nomag*`を使う意図の通り」とはなっていないので微妙なところです。

unicode-math使用の場合に`nomag*`が有用であることは絶対にないのか、というと、そうでもない気がします。

  * 「pLaTeXで`12pt`指定のときに本文がcmf12になるのが嫌（cmr10 at 12ptがいい）だから`nomag`でなく`nomag*`を指定する」ような人は、同じように「LuaLaTeXで`12pt`指定のときに本文がLMRoman12になるのが嫌だから`nomag*`を指定する」ことを考えるはず。
  * 「数式をUnicode文字で書きたい」人はunicode-mathを使うはず。
  * で、この2つは全く独立なので、両方行いたいという要望はありえる。

```tex
% LuaLaTeX文書, UTF-8
\documentclass[lualatex,ja=standard,nomag*,12pt]{bxjsarticle}
\usepackage{unicode-math}
\begin{document}

我輩は☃である。意味はまだ無い。
Lorem ipsum dolorかとんと見当がつかぬ。

ちなみに、$♡≺♧$であるが$♥⊀♣$であることに注意。

\end{document}
 ```

`nomag*`の需要が大きいとは思いませんが、要するに「`nomag`か`nomag*`か」の選択と「unicode-mathを使うか」の選択は無関係だということです。

**Comment by tats-u** [comment]
解決したのでCloseします。何も返信できずに申し訳ありませんでした。
