### ISSUE TITLE
[document] 2 small typos in the manual

### ISSUE THREAD

**Issue by cmplstofB** [zr-tex8r/BXjscls#9]
すいませんが，日本語で失礼します。
BXJSクラスの手引書に以下2点の小さな綴り誤りがあるようですので，報告させていただきます。

https://github.com/zr-tex8r/BXjscls/blob/542f8156cf11269552cb40c986d6fa11f10953a6/bxjscls-manual.tex#L174

「a5paper」→「a4paper」？

https://github.com/zr-tex8r/BXjscls/blob/542f8156cf11269552cb40c986d6fa11f10953a6/bxjscls-manual.tex#L595

「名雨」→「名前」？

**Comment by zr-tex8r** [comment]
（返事が遅くてすみません）

ご指摘の通りです。修正しました(2cf7b14a864129b66a04b12f3c40688f42fbb228)。

**Comment by cmplstofB** [comment]
ありがとうございます！
